# Generated by Django 4.2.16 on 2025-01-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="skin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("notes", models.CharField(max_length=255)),
            ],
        ),
    ]
