# Generated by Django 4.2.16 on 2025-01-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="class_skin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_id", models.SmallIntegerField(default=0)),
                ("class_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="class_tumor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_id", models.SmallIntegerField(default=0)),
                ("class_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="data_skin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("aitype", models.SmallIntegerField(default=1)),
                ("cls_type", models.SmallIntegerField(default=0)),
                ("imgpath", models.CharField(default=None, max_length=255, null=True)),
                ("img_bbox", models.TextField(default=None, null=True)),
                ("result_time", models.DateTimeField(auto_now_add=True)),
                ("delete_mask", models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="data_tumor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("aitype", models.SmallIntegerField(default=1)),
                ("cls_type", models.SmallIntegerField(default=0)),
                ("imgpath", models.CharField(default=None, max_length=255, null=True)),
                ("img_bbox", models.TextField(default=None, null=True)),
                ("result_time", models.DateTimeField(auto_now_add=True)),
                ("delete_mask", models.SmallIntegerField(default=1)),
            ],
        ),
    ]
