# Generated by Django 4.2.16 on 2025-01-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_class_skin_class_tumor_data_skin_data_tumor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="skin",
        ),
        migrations.RemoveField(
            model_name="data_skin",
            name="img_bbox",
        ),
    ]
