# Generated by Django 4.2.16 on 2025-01-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_delete_skin_remove_data_skin_img_bbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_skin",
            name="cls_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="data_tumor",
            name="cls_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
