# Generated by Django 4.2.16 on 2025-01-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_data_skin_cls_name_data_tumor_cls_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="class_skin",
            name="class_note",
            field=models.CharField(default="无", max_length=255),
        ),
    ]
