# Generated by Django 4.2.16 on 2025-01-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_class_skin_class_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255)),
                ("user_password", models.CharField(max_length=255)),
                ("touxiang", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
