# Generated by Django 4.2.16 on 2025-01-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user",
        ),
    ]
