# Generated by Django 4.2.16 on 2025-01-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("avator", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=32)),
                ("gender", models.CharField(max_length=8)),
                ("age", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("username", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
    ]
