# Generated by Django 5.1.7 on 2025-04-07 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userprofile_user_alter_facedetection_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='face_library/')),
                ('face_encoding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_faces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecognizedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='app.detectedface')),
                ('face_library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognitions', to='app.facelibrary')),
            ],
        ),
        migrations.DeleteModel(
            name='class_skin',
        ),
        migrations.DeleteModel(
            name='class_tumor',
        ),
        migrations.DeleteModel(
            name='data_skin',
        ),
        migrations.DeleteModel(
            name='data_tumor',
        ),
    ]
